### ISSUE TITLE
Build error: Duplicate symbol _relinkableLibraryClassesCount, _relinkableLibraryClasses in merged framework and bundle-file

### ISSUE THREAD

**Issue by Smartika29** [kateinoigakukun/MergeableLibraryInternals#2]
I am trying to use mergeable libraries in my test project. I am also using Bundle(for:) API in the test project. I am seeing build error for duplicate symbols ->  _relinkableLibraryClassesCount, _relinkableLibraryClasses. How did you get it working?

**Comment by kateinoigakukun** [comment]
Thank you for your interest. I might need to clarify this repository is just for my learning purpose, so this kind of platform questions might be better submitted to the Apple Feedback Assistant.
